# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RicercaIDEliminaFornitore.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EliminaFornitoreUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 171)
        MainWindow.setMinimumSize(QtCore.QSize(529, 171))
        MainWindow.setMaximumSize(QtCore.QSize(529, 171))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tornafornitori = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.tornafornitori.setGeometry(QtCore.QRect(30, 110, 161, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tornafornitori.setFont(font)
        self.tornafornitori.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tornafornitori.setObjectName("tornafornitori")
        self.ricercaidfornitore = QtWidgets.QLineEdit(self.centralwidget)
        self.ricercaidfornitore.setGeometry(QtCore.QRect(20, 60, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ricercaidfornitore.setFont(font)
        self.ricercaidfornitore.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"")
        self.ricercaidfornitore.setText("")
        self.ricercaidfornitore.setObjectName("ricercaidfornitore")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.eliminafornitore = QtWidgets.QPushButton(self.centralwidget)
        self.eliminafornitore.setGeometry(QtCore.QRect(350, 110, 161, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eliminafornitore.sizePolicy().hasHeightForWidth())
        self.eliminafornitore.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.eliminafornitore.setFont(font)
        self.eliminafornitore.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.eliminafornitore.setObjectName("eliminafornitore")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tornafornitori.setText(_translate("MainWindow", "Torna a Fornitori"))
        self.label.setText(_translate("MainWindow", "Inserisci l\'ID del fornitore da eliminare:"))
        self.eliminafornitore.setText(_translate("MainWindow", "Elimina"))
