# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeFornitori.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class HomeFornitoriUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.tabfornitori = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabfornitori.sizePolicy().hasHeightForWidth())
        self.tabfornitori.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabfornitori.setFont(font)
        self.tabfornitori.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 2px solid white;")
        self.tabfornitori.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabfornitori.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabfornitori.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabfornitori.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tabfornitori.setObjectName("tabfornitori")
        self.tabfornitori.setColumnCount(7)
        self.tabfornitori.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.tabfornitori)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.tornahome = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tornahome.sizePolicy().hasHeightForWidth())
        self.tornahome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tornahome.setFont(font)
        self.tornahome.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tornahome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tornahome.setObjectName("tornahome")
        self.gridLayout.addWidget(self.tornahome, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modfornitore = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modfornitore.sizePolicy().hasHeightForWidth())
        self.modfornitore.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        self.modfornitore.setFont(font)
        self.modfornitore.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.modfornitore.setObjectName("modfornitore")
        self.horizontalLayout.addWidget(self.modfornitore)
        self.aggfornitore = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aggfornitore.sizePolicy().hasHeightForWidth())
        self.aggfornitore.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.aggfornitore.setFont(font)
        self.aggfornitore.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.aggfornitore.setObjectName("aggfornitore")
        self.horizontalLayout.addWidget(self.aggfornitore)
        self.eliminafornitore = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eliminafornitore.sizePolicy().hasHeightForWidth())
        self.eliminafornitore.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        self.eliminafornitore.setFont(font)
        self.eliminafornitore.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.eliminafornitore.setObjectName("eliminafornitore")
        self.horizontalLayout.addWidget(self.eliminafornitore)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Lista Fornitori"))
        item = self.tabfornitori.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Fornitore"))
        item = self.tabfornitori.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome Azienda"))
        item = self.tabfornitori.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "e-mail"))
        item = self.tabfornitori.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tabfornitori.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Settore"))
        item = self.tabfornitori.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Città"))
        item = self.tabfornitori.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Via"))
        self.tornahome.setText(_translate("MainWindow", "Torna alla Home"))
        self.modfornitore.setText(_translate("MainWindow", "Modifica Info Fornitore"))
        self.aggfornitore.setText(_translate("MainWindow", " Aggiungi Fornitore"))
        self.eliminafornitore.setText(_translate("MainWindow", "Elimina Fornitore"))
        self.tabfornitori.setColumnWidth(0,150)
        self.tabfornitori.setColumnWidth(1,250)
        self.tabfornitori.setColumnWidth(2,300)
        self.tabfornitori.setColumnWidth(3,250)
        self.tabfornitori.setColumnWidth(4,250)
        self.tabfornitori.setColumnWidth(5,250)
        self.tabfornitori.setColumnWidth(6,300)



