# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestioneUtenti.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class GestioneUtentiUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.tabellaUtente = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabellaUtente.sizePolicy().hasHeightForWidth())
        self.tabellaUtente.setSizePolicy(sizePolicy)
        self.tabellaUtente.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabellaUtente.setFont(font)
        self.tabellaUtente.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 2px solid white;")
        self.tabellaUtente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabellaUtente.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabellaUtente.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabellaUtente.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tabellaUtente.setObjectName("tabelladip")
        self.tabellaUtente.setColumnCount(2)
        self.tabellaUtente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabellaUtente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabellaUtente.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tabellaUtente, 1, 0, 1, 3)
        self.tornahome = QtWidgets.QCommandLinkButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tornahome.setFont(font)
        self.tornahome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tornahome.setObjectName("tornahome")
        self.gridLayout.addWidget(self.tornahome, 2, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.aggutente = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.aggutente.setFont(font)
        self.aggutente.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.aggutente.setObjectName("aggutente")
        self.verticalLayout.addWidget(self.aggutente)
        self.eliminautente = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.eliminautente.setFont(font)
        self.eliminautente.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.eliminautente.setObjectName("eliminautente")
        self.verticalLayout.addWidget(self.eliminautente)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Lista Utenti:"))
        item = self.tabellaUtente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CF Dipendente"))
        item = self.tabellaUtente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        self.tornahome.setText(_translate("MainWindow", "Torna alla Home"))
        self.aggutente.setText(_translate("MainWindow", "Aggiungi Utente"))
        self.eliminautente.setText(_translate("MainWindow", "Elimina Utente"))
        self.tabellaUtente.setColumnWidth(0, 350)
        self.tabellaUtente.setColumnWidth(1, 350)