# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiqFinale.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Soci.Model.ModelSocio import ModelSocio


class LiquiditaHomeUI(object):
    def setupUi(self, MainWindow):
        self.modelSoci = ModelSocio()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1913, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.tabliquidita = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabliquidita.sizePolicy().hasHeightForWidth())
        self.tabliquidita.setSizePolicy(sizePolicy)
        self.tabliquidita.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabliquidita.setFont(font)
        self.tabliquidita.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 1px solid white;")
        self.tabliquidita.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabliquidita.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabliquidita.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabliquidita.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tabliquidita.setObjectName("tabliquidita")
        self.tabliquidita.setColumnCount(6)
        self.tabliquidita.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabliquidita.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabliquidita.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabliquidita.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabliquidita.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        item.setFont(font)
        self.tabliquidita.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabliquidita.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tabliquidita, 1, 0, 1, 2)
        self.tabsoci = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabsoci.setFont(font)
        self.tabsoci.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 1px solid white;")
        self.tabsoci.setObjectName("tabsoci")
        self.tabsoci.setColumnCount(2)
        self.tabsoci.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabsoci.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabsoci.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tabsoci, 1, 2, 1, 1)
        self.tabfornitori = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabfornitori.setFont(font)
        self.tabfornitori.setStyleSheet("border-radius: 2px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 1px solid white;")
        self.tabfornitori.setObjectName("tabfornitori")
        self.tabfornitori.setColumnCount(2)
        self.tabfornitori.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabfornitori.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tabfornitori, 1, 3, 1, 1)
        self.tornahome = QtWidgets.QCommandLinkButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.tornahome.setFont(font)
        self.tornahome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        icon = QtGui.QIcon.fromTheme("null")
        self.tornahome.setIcon(icon)
        self.tornahome.setObjectName("tornahome")
        self.gridLayout.addWidget(self.tornahome, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insentrata = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insentrata.sizePolicy().hasHeightForWidth())
        self.insentrata.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        self.insentrata.setFont(font)
        self.insentrata.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.insentrata.setObjectName("insentrata")
        self.horizontalLayout.addWidget(self.insentrata)
        self.insuscita = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insuscita.sizePolicy().hasHeightForWidth())
        self.insuscita.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        self.insuscita.setFont(font)
        self.insuscita.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.insuscita.setObjectName("insuscita")
        self.horizontalLayout.addWidget(self.insuscita)
        self.statistiche = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statistiche.sizePolicy().hasHeightForWidth())
        self.statistiche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        self.statistiche.setFont(font)
        self.statistiche.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.statistiche.setObjectName("statistiche")
        self.horizontalLayout.addWidget(self.statistiche)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loadSoci()
        self.loadFornitori()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Gestione Liquidità"))
        item = self.tabliquidita.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Categoria"))
        item = self.tabliquidita.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "€"))
        item = self.tabliquidita.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tabliquidita.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ID Socio"))
        item = self.tabliquidita.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ID Fornitore"))
        item = self.tabliquidita.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Note"))
        item = self.tabsoci.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Socio"))
        item = self.tabsoci.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome Socio"))
        item = self.tabfornitori.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Fornitore"))
        item = self.tabfornitori.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome Fornitore"))
        self.tornahome.setText(_translate("MainWindow", "Torna alla Home"))
        self.insentrata.setText(_translate("MainWindow", "Inserisci Entrata "))
        self.insuscita.setText(_translate("MainWindow", "Inserisci Uscita "))
        self.statistiche.setText(_translate("MainWindow", "Statistiche"))

        self.tabliquidita.setColumnWidth(2, 210)
        self.tabliquidita.setColumnWidth(4, 180)
        self.tabliquidita.setColumnWidth(5, 350)
        self.tabfornitori.setColumnWidth(0, 150)
        self.tabfornitori.setColumnWidth(1, 250)
        self.tabsoci.setColumnWidth(0, 130)
        self.tabsoci.setColumnWidth(1, 270)

    def loadFornitori(self):
        query = "SELECT id_fornitore, nome_azienda FROM Fornitori"
        rowindex = 0

        self.tabfornitori.setRowCount(80)

        for row in self.modelSoci.c.execute(query):
            id = row[0]
            conv_id = str(id)
            self.tabfornitori.setItem(rowindex, 0, QtWidgets.QTableWidgetItem(conv_id))
            self.tabfornitori.setItem(rowindex, 1, QtWidgets.QTableWidgetItem(row[1]))
            rowindex += 1

    def loadSoci(self):
        query = "SELECT id_socio, nome_cliente, cognome_cliente FROM Soci "

        rowindex = 0
        self.tabsoci.setRowCount(80)

        for row in self.modelSoci.c.execute(query):
            id_socio = row[0]
            conv_id = str(id_socio)
            self.tabsoci.setItem(rowindex, 0, QtWidgets.QTableWidgetItem(conv_id))
            self.tabsoci.setItem(rowindex, 1, QtWidgets.QTableWidgetItem(row[1] + " " + row[2]))
            rowindex += 1



