# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EliminaDipendente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EliminaDipUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 256)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tornagestdip = QtWidgets.QCommandLinkButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tornagestdip.sizePolicy().hasHeightForWidth())
        self.tornagestdip.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tornagestdip.setFont(font)
        self.tornagestdip.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tornagestdip.setObjectName("tornagestdip")
        self.horizontalLayout.addWidget(self.tornagestdip, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.confermaricercacf = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confermaricercacf.sizePolicy().hasHeightForWidth())
        self.confermaricercacf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        self.confermaricercacf.setFont(font)
        self.confermaricercacf.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 155);\n"
"}\n"
"")
        self.confermaricercacf.setObjectName("confermaricercacf")
        self.horizontalLayout.addWidget(self.confermaricercacf)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ricercacf = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ricercacf.sizePolicy().hasHeightForWidth())
        self.ricercacf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        self.ricercacf.setFont(font)
        self.ricercacf.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(221, 214, 73);\n"
"border: 3px solid white;\n"
"")
        self.ricercacf.setText("")
        self.ricercacf.setReadOnly(False)
        self.ricercacf.setObjectName("ricercacf")
        self.verticalLayout.addWidget(self.ricercacf)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tornagestdip.setText(_translate("MainWindow", "Torna a Gestione dipendenti"))
        self.confermaricercacf.setText(_translate("MainWindow", "CONFERMA"))
        self.label.setText(_translate("MainWindow", "Inserisci il C.F. del dipendente da rimuovere:"))
